server.port=8080
spring.application.name=pulse-check-api

spring.profiles.active=dev

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

sweeper.interval.ms=60000

logging.level.com.critmon.pulsecheck=INFO
