server.port=8080
spring.application.name=pulse-check-api

# H2 In-Memory Database (for testing)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password="California123!"

# JPA Configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Console (for debugging - access at http://localhost:8080/h2-console)
spring.h2.console.enabled=true

logging.level.com.critmon.pulsecheck=INFO
